#Da un wp a un altro conto di ottenere 6 misure da Navigazione 
#ATT. HO SALTATO LA FASE DI APPROACH

lld_seq:
 time0: #stima della posizione iniziale. verso il wp[1], a cui ci si arriva con strategia 1. I primi 13 messaggi lld (vedi sotto) sono uguali a quelli della posizione iniziale
    latitude: 45.110730             #[°]
    longitude: 7.640815             #[°]
    depth: 0.5                     #[m]
 time1: 
    latitude: 45.110730             #[°]
    longitude: 7.640815             #[°]
    depth: 0.5                     #[m]
 time2: 
    latitude: 45.110730             #[°]
    longitude: 7.640815             #[°]
    depth: 0.5                     #[m]
 time3: 
    latitude: 45.110730             #[°]
    longitude: 7.640815             #[°]
    depth: 0.5                     #[m]
 time4: 
    latitude: 45.110730             #[°]
    longitude: 7.640815             #[°]
    depth: 0.5                     #[m]
 time5: 
    latitude: 45.110730             #[°]
    longitude: 7.640815             #[°]
    depth: 0.5                     #[m]
 time6: 
    latitude: 45.110730             #[°]
    longitude: 7.640815             #[°]
    depth: 0.5                     #[m]
 time7: 
    latitude: 45.110730             #[°]
    longitude: 7.640815             #[°]
    depth: 0.5                     #[m]
 time8: 
    latitude: 45.110730             #[°]
    longitude: 7.640815             #[°]
    depth: 0.5                     #[m]
 time9: 
    latitude: 45.110730             #[°]
    longitude: 7.640815             #[°]
    depth: 0.5                     #[m]
 time10: 
    latitude: 45.110730             #[°]
    longitude: 7.640815             #[°]
    depth: 0.5                     #[m]
 time11: 
    latitude: 45.110730             #[°]
    longitude: 7.640815             #[°]
    depth: 0.5                     #[m]
 time12: 
    latitude: 45.110730             #[°]
    longitude: 7.640815             #[°]
    depth: 0.5                     #[m]
 time13: 
    latitude: 45.110730             #[°]
    longitude: 7.640815             #[°]
    depth: 0.5                     #[m]
 time14: #finita la fase di aggiustamento orientazione, inizia SURGE. Cambia la posizione 
#obiettivo: latitude: 45.109306             
#    	    longitude: 7.640577
#           depth :10
    latitude: 45.110377             #[°]
    longitude: 7.640760             #[°]
    depth: 2.88815                     #[m]
 time15: #finita la fase di aggiustamento orientazione, inizia SURGE. Camba la posizione
    latitude: 45.110020             #[°]
    longitude: 7.640695             #[°]
    depth: 2.88815*2                     #[m]
 time16: #finita la fase di aggiustamento orientazione, inizia SURGE. Camba la posizione
    latitude: 45.109655             #[°]
    longitude: 7.640637             #[°]
    depth: 2.88815*3                     #[m]
 time17: #finita la fase di aggiustamento orientazione, inizia SURGE. Camba la posizione
    latitude: 45.109310             #[°]
    longitude: 7.640579             #[°]
    depth: 10.5                     #[m]

	
rpy_seq: #un messaggio al secondo. ogni secondo si veicolo spazza 17°
  time0:
	roll: 0
	pitch: 0
	yaw: 0
  time1:
	roll: 0
	pitch: 0
	yaw: 17
   time2:
	roll: 0
	pitch: 0
	yaw: 34
   time3:
	roll: 0
	pitch: 0
	yaw: 51
   time4:
	roll: 0
	pitch: 0
	yaw: 68
   time5:
	roll: 0
	pitch: 0
	yaw: 85
   time6:
	roll: 0
	pitch: 0
	yaw: 102
   time7:
	roll: 0
	pitch: 0
	yaw: 119
   time8:
	roll: 0 
	pitch: 0
	yaw: 135
   time9:
	roll: 0
	pitch: 0
	yaw: 156
   time10:
	roll: 0
	pitch: 0
	yaw: 171
   time11:
	roll: 0
	pitch: 0
	yaw: 187
   time12: #finita la fase di YAW, il task manager dovrebbe rilevare il passaggio alla fase successiva di PITCH
	roll: 0
	pitch: 2
	yaw: 187
   time13:
	roll: 0
	pitch: 4
	yaw: 187
   time14: #finita la fase di PITCH , segue la fase di SURGE => messaggi successivi di rpy rimangono uguali
	roll: 0
	pitch: 4
	yaw: 187
   time15:
	roll: 0
	pitch: 4
	yaw: 187
   time16:
	roll: 0
	pitch: 4
	yaw: 187
   time17:
	roll: 0
	pitch: 4
	yaw: 187
 

lin_vel_seq:
   time0:
	vx: 0
	vy: 0
	vz: 0
   time1:
	vx: 0
	vy: 0
	vz: 0
   time2:
	vx: 0
	vy: 0
	vz: 0
   time3:
	vx: 0
	vy: 0
	vz: 0
   time4:
	vx: 0
	vy: 0
	vz: 0
   time5:
	vx: 0
	vy: 0
	vz: 0
   time6:
	vx: 0
	vy: 0
	vz: 0
   time7:
	vx: 0
	vy: 0
	vz: 0
   time8:
	vx: 0
	vy: 0
	vz: 0
   time9:
	vx: 0
	vy: 0
	vz: 0
   time10:
	vx: 0
	vy: 0
	vz: 0
   time11:
	vx: 0
	vy: 0
	vz: 0
   time12:
	vx: 0
	vy: 0
	vz: 0
   time13:
	vx: 0
	vy: 0
	vz: 0
   time14:
	vx: 3
	vy: 0
	vz: 0
   time15:
	vx: 3
	vy: 0
	vz: 0
   time16:
	vx: 3
	vy: 0 
	vz: 0
   time17:
	vx: 3
	vy: 0
	vz: 0
