initial_pose:
  orientation: 
    pitch: 0.0                      #[rad]
    roll: 0.0                       #[rad]
    yaw: 0.0                        #[rad]
  position: 
    latitude: 43.533200             #[°]
    longitude: 10.299219             #[°]
    depth: 0.0                      #[m]
  
waypoint_list: 
  wp1:
    latitude: 43.530516             #[°]
    longitude: 10.299340             #[°]
    depth: 15.0                     #[m]
  wp2:
    latitude: 43.528184             #[°]
    longitude: 10.295031             #[°]
    depth: 25.0                     #[m]
  wp3:
    latitude: 43.528051             #[°]
    longitude: 10.289872             #[°]
    depth: 17.0                     #[m]
  wp4:
    latitude: 43.531616             #[°]
    longitude: 10.286534             #[°]
    depth: 30.0                     #[m]
  wp5:
    latitude: 43.534828             #[°]
    longitude: 10.294606             #[°]
    depth: 0.0                      #[m]

tolerance_on_waypoint: 10           #[m]    same as error_tolerances_list/APPROACH in task_manager.yaml

