
initial_pose:
  orientation: 
    pitch: 0.0                      #[rad]
    roll: 0.0                       #[rad]
    yaw: 0.0                        #[rad]
  position: 
    latitude: 45.110735             #[°]
    longitude: 7.640827             #[°]
    depth: 0.0                      #[m]
  
waypoint_list: 
  wp1:
    latitude: 45.109306             #[°]
    longitude: 7.640577             #[°]
    depth: 10.0                     #[m]
  wp2:
    latitude: 45.109874             #[°]
    longitude: 7.640883             #[°]
    depth: 20.0                     #[m]
  wp3:
    latitude: 45.109340             #[°]
    longitude: 7.641342             #[°]
    depth: 20.0                     #[m]
  wp4:
    latitude: 45.109874             #[°]
    longitude: 7.641696             #[°]
    depth: 20.0                     #[m]
  wp5:
    latitude: 45.109357             #[°]
    longitude: 7.642082             #[°]
    depth: 0.0                      #[m]

tolerance_on_waypoint: 10           #[m]    same as APPROACH in task_manager.yaml


