UP_SAT:   100
DOWN_SAT: -100

gains_P:
  YAW:        [5, 5, 30, 0, 10, 15]
  PITCH:      [5, 5, 30, 0, 80, 15]
  HEAVE:      [5, 5, 10, 0, 10, 15]
  SURGE:      [50, 10, 30, 0, 80, 15]
  APPROACH:   [5, 5, 30, 0, 10, 15]

gains_I:
  YAW:        [0, 0, 0.2, 0, 0.1, 0.1]
  PITCH:      [0, 0, 0.2, 0, 0.5, 0.1]
  HEAVE:      [0, 0, 0.1, 0, 0.1, 0.1]
  SURGE:      [5, 0, 0.2, 0, 0.5, 0.1]
  APPROACH:   [0, 0, 0.2, 0, 0.1, 0.1]
