UP_SAT:    [ 100, 100, 100, 0, 45, 45]         # [ [N], [N], [N], [Nm], [Nm], [Nm] ]
DOWN_SAT:  [-80, -80, -80, 0, -45, -45]        # [ [N], [N], [N], [Nm], [Nm], [Nm] ]

gains_P:
  YAW:          [  5,   5,  15,  0,   0,   1]
  PITCH:        [  5,   5,  15,  0,   1,   1]
  HEAVE:        [  5,   5,  15,  0,   0,   1]
  SURGE_1:      [ 50,   5,  15,  0,   1,   1]
  SURGE_2:      [ 50,   5,  15,  0,   0,   1]
  APPROACH:     [  5,   5,  15,  0,   0,   1]

gains_I:
  YAW:          [  0.1,   0.1, 0.5,  0,   0,  0]
  PITCH:        [  0.1,   0.1, 0.5,  0,   1,  0]
  HEAVE:        [  0.1,   0.1, 0.5,  0,   0,  0]
  SURGE_1:      [    5,   0.1, 0.5,  0,   1,  0]
  SURGE_2:      [    5,   0.1, 0.5,  0,   0,  0]
  APPROACH:     [  0.1,   0.1, 0.5,  0,   0,  0]
