UP_SAT:   100
DOWN_SAT: -100

gains_P:
  YAW:        [5, 15, 15, 0, 50, 90]
  PITCH:      [5, 15, 15, 0, 50, 5]
  HEAVE:      [5, 5, 50, 0, 50, 10]
  SURGE:      [100, 30, 80, 0, 50, 10]
  APPROACH:   [5, 5, 50, 0, 50, 2]

gains_I:
  YAW:        [0, 0, 0.1, 0, 20, 0.1]
  PITCH:      [0, 0, 0.1, 0, 20, 0.1]
  HEAVE:      [0, 0, 0.1, 0, 20, 0.1]
  SURGE:      [20, 0, 0.1, 0, 20, 0.1]
  APPROACH:   [0.1, 0.1, 0.1, 0, 20, 0.1]




