UP_SAT:    100
DOWN_SAT: -100

gains_P:
  YAW:          [  5,   5,  30,  0,   0,  5]
  PITCH:        [  5,   5,  30,  0,  50,  5]
  HEAVE:        [  5,   5,  30,  0,   0,  5]
  SURGE_1:      [ 50,  10,  30,  0,  50,  5]
  SURGE_2:      [ 50,  10,  30,  0,   0,  5]
  APPROACH:     [  5,   5,  30,  0,   0,  5]

gains_I:
  YAW:          [  0.1,   0.1, 0.25,  0,   0,  0.1]
  PITCH:        [  0.1,   0.1, 0.25,  0,   5,  0.1]
  HEAVE:        [  0.1,   0.1, 0.25,  0,   0,  0.1]
  SURGE_1:      [    5,   0.1, 0.25,  0,   5,  0.1]
  SURGE_2:      [    5,   0.1, 0.25,  0,   0,  0.1]
  APPROACH:     [  0.1,   0.1, 0.25,  0,   0,  0.1]
