task_velocity_reference_list:
  YAW:      0.1                     # [rad/s]
  PITCH:    0.1                     # [rad/s]
  HEAVE:    0.5                     # [m/s]
  SURGE:    1                       # [m/s]
  APPROACH: 0.2                    # [m/s]

