task_velocity_reference_list:
  YAW:            0.2                  # [rad/s]
  PITCH:          0.2                  # [rad/s]
  HEAVE:            5                  # [m/s]
  SURGE:          0.5                  # [m/s]
  APPROACH:         1                  # [m/s] #0.2

references:
  SURGE:
     high:                    1        # [m/s]
     low:                   0.2        # [m/s]
     tolerance:             0.1        # [m/s]
     distance_tolerance:     35        # [m]
