task_velocity_reference_list:
  YAW:            0.1                  # [rad/s]
  PITCH:          0.1                  # [rad/s]
  HEAVE:          0.5                  # [m/s]
  SURGE:          0.1                  # [m/s]
  APPROACH:       0.1                  # [m/s]

references:
  SURGE:
     high:                    1        # [m/s]
     low:                   0.2        # [m/s]
     tolerance:             0.1        # [m/s]
     distance_tolerance:     35        # [m]
