task_velocity_reference_list:
  YAW:      0.1                     # [rad/s]
  PITCH:    0.1                     # [rad/s]
  HEAVE:    0.2                     # [m/s]
  SURGE:    0.25                    # [m/s]
  APPROACH: 0.5                     # [m/s]

references:
  SURGE:
     final:       1                 # [m/s]
     tolerance: 0.1                 # [m/s]
