critical_pitch: 20                  #[°]

task_seq_list:                      # strategy 0: not set - init
  ts1:                              # strategy 1: pitch_des < critical_pitch
    - YAW   
    - PITCH   
    - SURGE
    - APPROACH
  ts2:                              # strategy 2: pitch_des > critical_pitch
    - PITCH
    - YAW    
    - HEAVE
    - SURGE
    - APPROACH

approach_radius: 20                  #[m]

error_tolerances_list:
  YAW:       3                      #[°]
  PITCH:     3                      #[°]
  HEAVE:     5                      #[m]
  SURGE:     5                      #[m]
  APPROACH: 10                      #[m]    same as tolerance_on_waypoint in mission.yaml
