critical_pitch: 20                  # [°]
critical_depth: 3                   # [m]

task_seq_list:                      # strategy 0: not set - init
  ts1:                              # strategy 1: pitch_des < critical_pitch
    - YAW   
    - PITCH   
    - SURGE
    - APPROACH
  ts2:                              # strategy 2: pitch_des > critical_pitch
    - PITCH                         # set pitch to 0
    - YAW    
    - HEAVE
    - SURGE
    - APPROACH

task_tolerance_list:
  YAW:       3                      # [°]
  PITCH:     3                      # [°]
  HEAVE:     3                      # [m]
  SURGE:    30                      # [m]
  APPROACH: 10                      # [m]    same as tolerance_on_waypoint in mission.yaml


